/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.marstor.msa.common.treeNode;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashSet;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Administrator
 */
public class JavaDBConnect {
    Connection conn = null;
    
    public Connection getConnection(){
        return conn;
    }

    public boolean connect() {
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver").newInstance();
            Properties props = new Properties();
            props.put("user", "root");
            props.put("password", "root");
            conn = DriverManager.getConnection("jdbc:derby:/var/msa/ecd;", props);
        } catch (Exception ex) {
            Logger.getLogger(JavaDBConnect.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
        return true;
    }

    public boolean createTable() {
        try {
            Statement statement = conn.createStatement();
            int result = statement.executeUpdate("create table log (id BIGINT not null generated by default as identity,datetime bigint,logid bigint,"
                    + "type int,username varchar(32) ,parameters varchar(1024),flag int,moduleID int )");
            System.out.println("result " + result);
        } catch (SQLException ex) {
            Logger.getLogger(JavaDBConnect.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        } finally {
            try {
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(JavaDBConnect.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return true;
    }

    public boolean insert(int groupNum, int userNum) {
        try {
            PreparedStatement statement = conn
                    .prepareStatement("insert into License_Info (id, user_num, group_num) values(?,?,?)");
            statement.setInt(1, 1);
            statement.setInt(2, groupNum);
            statement.setInt(3, userNum);
            statement.execute();
        } catch (SQLException ex) {
            Logger.getLogger(JavaDBConnect.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        } finally {
            try {
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(JavaDBConnect.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return true;
    }
    
    public boolean update(int groupNum, int userNum) {
        try {
            PreparedStatement statement = conn
                    .prepareStatement("UPDATE License_Info SET user_num=?, group_num=? WHERE id=1");
            statement.setInt(1, userNum);
            statement.setInt(2, groupNum);
            statement.execute();
        } catch (SQLException ex) {
            Logger.getLogger(JavaDBConnect.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        } finally {
            try {
                conn.close();
                DriverManager.getConnection("jdbc:derby:/var/msa/ecd;shutdown=true");
            } catch (SQLException ex) {
                Logger.getLogger(JavaDBConnect.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return true;
    }

    public boolean query() {
        try {
            Statement statement = conn.createStatement();
            ResultSet rs = statement.executeQuery("select * from log");
            while (rs.next()) {
                System.out.println(rs.getLong(1));
                System.out.println(rs.getLong(2));
                System.out.println(rs.getLong(3));
                System.out.println(rs.getInt(4));
                System.out.println(rs.getString(5));
                System.out.println(rs.getString(6));
                System.out.println(rs.getInt(7));
                System.out.println(rs.getInt(8));
            }

        } catch (SQLException ex) {
            Logger.getLogger(JavaDBConnect.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        } finally {
            try {
                if (conn == null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                Logger.getLogger(JavaDBConnect.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return true;
    }

    public Boolean doesTableExist(String tablename) {
        connect();
        HashSet<String> set = new HashSet<String>();
        try {
            DatabaseMetaData meta = conn.getMetaData();
            ResultSet res = meta.getTables(null, null, null,
                    new String[]{"TABLE"});
            while (res.next()) {
                set.add(res.getString("TABLE_NAME"));
            }
            res.close();
            conn.close();
        } catch (Exception e) {
            System.err.println("Exception: " + e.getMessage());
        }
        //System.out.println(set);
        return set.contains(tablename.toUpperCase());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        JavaDBConnect db = new JavaDBConnect();
        if (args.length != 0 && args[0].equals("create")) {
            db.connect();
            db.createTable();
//        } else if (args.length != 0 && args[0].equals("insert")) {
//            db.connect();
//            db.insert();
//        } else {
//            db.connect();
//            db.query();
        }
        System.out.println(db.doesTableExist("mylog"));
    }

    public PreparedStatement prepareStatement(String insert_into_log_datetimelogidtypeusername) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
